// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YTH_backend.Data;

#nullable disable

namespace YTH_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231122836_AddedPriceToCourse")]
    partial class AddedPriceToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YTH_backend.Models.Course.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("Link")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.Course.UserCourseRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_user_course_registration_course_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_course_registration_user_id");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_course_registration_user_id_course_id");

                    b.ToTable("user_course_registration", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.Event.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_notifications_date");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.Event.UserEventRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_user_event_registration_event_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_event_registration_user_id");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_event_registration_user_id_event_id");

                    b.ToTable("user_event_registrations", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.ExpertApplication.ExpertApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("bool")
                        .HasColumnName("is_approved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("ResolutionMessage")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("resolution_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedBy");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_expert_applications_user_id");

                    b.ToTable("expert_applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_expert_applications_status_fields_consistency", "(\r\n                   (status IN ('Created','Sent') AND accepted_by IS NULL AND is_approved IS NULL AND resolution_message IS NULL)\r\n                   OR\r\n                   (status = 'AcceptedForReview' AND accepted_by IS NOT NULL AND is_approved IS NULL AND resolution_message IS NULL)\r\n                   OR\r\n                   (status = 'Reviewed' AND accepted_by IS NOT NULL AND is_approved IS NOT NULL AND resolution_message IS NOT NULL)\r\n                 )");
                        });
                });

            modelBuilder.Entity("YTH_backend.Models.ExpertApplication.ExpertApplicationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExpertApplicationActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("expert_application_action_type");

                    b.Property<Guid>("ExpertApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_application_id");

                    b.Property<string>("Other")
                        .HasColumnType("jsonb")
                        .HasColumnName("other");

                    b.HasKey("Id");

                    b.HasIndex("ExpertApplicationId");

                    b.ToTable("expert_application_action", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.Post.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("image_url");

                    b.Property<string>("PostStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.User.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.User.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("YTH_backend.Models.Course.UserCourseRegistration", b =>
                {
                    b.HasOne("YTH_backend.Models.Course.Course", "Course")
                        .WithMany("UserCourseRegistration")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_course_registration_course_id");

                    b.HasOne("YTH_backend.Models.User.User", "User")
                        .WithMany("UserCourseRegistration")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_course_registration_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YTH_backend.Models.Event.UserEventRegistration", b =>
                {
                    b.HasOne("YTH_backend.Models.Event.Event", "Event")
                        .WithMany("UserEventRegistration")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_event_registrations_events");

                    b.HasOne("YTH_backend.Models.User.User", "User")
                        .WithMany("UserEventRegistration")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_event_registrations_users");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YTH_backend.Models.ExpertApplication.ExpertApplication", b =>
                {
                    b.HasOne("YTH_backend.Models.User.User", "AcceptedByUser")
                        .WithMany("AcceptedByExpertApplications")
                        .HasForeignKey("AcceptedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expert_applications_users_accepted_by");

                    b.HasOne("YTH_backend.Models.User.User", "User")
                        .WithMany("ExpertApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expert_applications_users");

                    b.Navigation("AcceptedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YTH_backend.Models.ExpertApplication.ExpertApplicationAction", b =>
                {
                    b.HasOne("YTH_backend.Models.ExpertApplication.ExpertApplication", "ExpertApplication")
                        .WithMany("Actions")
                        .HasForeignKey("ExpertApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expert_application_action_expert_application");

                    b.Navigation("ExpertApplication");
                });

            modelBuilder.Entity("YTH_backend.Models.Post.Post", b =>
                {
                    b.HasOne("YTH_backend.Models.User.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_posts_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YTH_backend.Models.User.Notification", b =>
                {
                    b.HasOne("YTH_backend.Models.User.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_notifications");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YTH_backend.Models.User.RefreshToken", b =>
                {
                    b.HasOne("YTH_backend.Models.User.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YTH_backend.Models.Course.Course", b =>
                {
                    b.Navigation("UserCourseRegistration");
                });

            modelBuilder.Entity("YTH_backend.Models.Event.Event", b =>
                {
                    b.Navigation("UserEventRegistration");
                });

            modelBuilder.Entity("YTH_backend.Models.ExpertApplication.ExpertApplication", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("YTH_backend.Models.User.User", b =>
                {
                    b.Navigation("AcceptedByExpertApplications");

                    b.Navigation("ExpertApplications");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserCourseRegistration");

                    b.Navigation("UserEventRegistration");
                });
#pragma warning restore 612, 618
        }
    }
}
